### ISSUE TITLE
ExtUtils::MakeMaker version

### ISSUE THREAD

**Issue by jwittkoski** [tokuhirom/Test-SharedFork#18]
I noticed that the recent switch to EUMM requires version 6.64. Is there a specific need to use 6.64 or will earlier version(s) work correctly also?

**Comment by JJ** [comment]
@jwittkoski please check tokuhirom/Test-TCP#29 for an answer to this.

**Comment by jwittkoski** [comment]
Yeah, that's fine. Like my comment in https://github.com/tokuhirom/Test-TCP/issues/29:
To be clear, this wasn't causing any problems. Originally I was asking because in one of my projects it was the only library dependency forcing EUMM to be a newer version than the one in core (5.16.x). I noticed commit eafc490f937ad42e65135e9e3103aaea9efb70f9 bumped the required EUMM version and I was just wondering if it was needed or an inadvertent side effect of the change in build process.
